# Generated by Django 5.2 on 2025-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_popularmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTMDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about_tmdb/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Блок О TMDb',
                'verbose_name_plural': 'Блоки О TMDb',
            },
        ),
    ]
